### ISSUE TITLE
Laminas update

### ISSUE THREAD

**Issue by reinfi** [goaop/goaop-zf2-module#15]
Hey!

Should we update this library to laminas or add a new package because it contains zf2 in its name?

**Comment by icanhazstring** [comment]
Would simply create a new one to avoid name confusion. Maybe we could also abandon this one then. Same as zend packages got abandoned.

**Comment by DannyMeyer** [comment]
Sadly I wasn't able to transfer it into the goaop scope, so I had to keep the migration in my scope: https://github.com/DannyMeyer/goaop-laminas-module

Feel free to clone it back into the correct scope :)

**Comment by icanhazstring** [comment]
@lisachenko could you invite him to move the repo?

**Comment by icanhazstring** [comment]
Done with https://github.com/goaop/goaop-laminas-module and v3.0. Thanks @DannyMeyer
